apiVersion: v1
kind: ConfigMap
metadata:
  name: autocare-backend-config
  namespace: autocare-advisor
data:
  NODE_ENV: 'production'
  PORT: '3000'
  CORS_ORIGIN: 'https://app.autocare-advisor.com,https://admin.autocare-advisor.com'
  API_RATE_LIMIT: '1000'
  API_TIMEOUT: '30000'
  LOG_LEVEL: 'info'
  LOG_FILE_SIZE: '10MB'
  LOG_MAX_FILES: '5'
  NODE_OPTIONS: '--max-old-space-size=1536'
  UV_THREADPOOL_SIZE: '8'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: autocare-db
data:
  postgresql.conf: |
    # PostgreSQL Configuration for AutoCare Advisor
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    shared_buffers = 256MB
    effective_cache_size = 1GB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 4MB
    min_wal_size = 1GB
    max_wal_size = 4GB

    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = 'log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'error'
    log_min_error_statement = error
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: autocare-db
data:
  mongod.conf: |
    # MongoDB Configuration for AutoCare Advisor
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    net:
      bindIp: 0.0.0.0
      port: 27017
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    security:
      authorization: enabled
    replication:
      replSetName: autocare-replica
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: autocare-db
data:
  redis.conf: |
    # Redis Configuration for AutoCare Advisor
    port 6379
    bind 0.0.0.0
    dir /data

    # Persistence
    appendonly yes
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000

    # Memory management
    maxmemory 400mb
    maxmemory-policy allkeys-lru

    # Performance
    tcp-keepalive 300
    timeout 0
