apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocare-frontend
  namespace: autocare-advisor
  labels:
    app: autocare-frontend
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: autocare-frontend
  template:
    metadata:
      labels:
        app: autocare-frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: autocare/frontend:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: 'production'
            - name: NEXT_PUBLIC_API_URL
              value: 'http://backend-service.autocare-advisor.svc.cluster.local:5001'
            - name: PORT
              value: '3000'
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '300m'
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
      initContainers:
        - name: wait-for-backend
          image: curlimages/curl:latest
          command:
            [
              'sh',
              '-c',
              'until curl -f http://backend-service.autocare-advisor.svc.cluster.local:5001/health; do echo waiting for backend; sleep 2; done;',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: autocare-advisor
  labels:
    app: autocare-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: autocare-frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: autocare-advisor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autocare-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
